### ISSUE TITLE
Crash when runnig gcov

### ISSUE THREAD

**Issue by matsch82** [zero9178/C-Cpp-Coverage-for-CLion#11]
Crash happens with 2.0.2

`gcov returned error code -1073741819 (Invocation and error output:): Invocation: C:\MinGW\bin\gcov.exe -i -m -b C:\git\XXXXXXXX\build\debug-gcc\external\googletest\googlemock\CMakeFiles\gmock.dir\src\gmock-all.cc.gcda C:\git\XXXXXXXX\build\debug-gcc\external\googletest\googlemock\gtest\CMakeFiles\gtest.dir\src\gtest-all.cc.gcda ....`

Same setup worked with 1.1.3
gcov (MinGW.org GCC-6.3.0-1) 6.3.0

**Comment by zero9178** [comment]
Could you try going into the settings and disabling Branch coverage? gcov prior to version 9 has been rather unstable in my experience (at least on MinGW) but supposedly this should help a bit. Prior to 2.1.0 I stupidly passed the -b flag even though branch coverage for versions prior of 9 is not implemented.
