### ISSUE TITLE
Small suggestion: Clearer tooltip on the Run action?

### ISSUE THREAD

**Issue by claremacrae** [zero9178/C-Cpp-Coverage-for-CLion#23]
Here's another location where it's not obvious that the action is specific to this plugin...

![image](https://user-images.githubusercontent.com/4840096/107507567-abb60a80-6b97-11eb-81aa-8e313676a698.png)

I wonder about mentioning that it's the plugin - perhaps:

"Run [exe] with C/C++ Coverage Plugin"

**Comment by zero9178** [comment]
![image](https://user-images.githubusercontent.com/6625526/107544154-39125280-6bca-11eb-9d21-da4b5336e7df.png)
Will be included in the release tomorrow morning!

**Comment by claremacrae** [comment]
Looks good! Thank you.
