### ISSUE TITLE
Unknown command line argument

### ISSUE THREAD

**Issue by bennybbb** [zero9178/C-Cpp-Coverage-for-CLion#4]
Whenever I try to exeucte the coverage I get the following errror message:

gcov returned following warning:
			gcov: Unknown command line argument '-i'.  Try: '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/gcov -help'
			Did you mean '-a'?
			gcov: Unknown command line argument '-m'.  Try: '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/gcov -help'
			Did you mean '-a'?

I am using CLion 2018.3.3 with Mojave 10.14 and gcov: Apple LLVM version 10.0.0 (clang-1000.11.45.5)

**Comment by zero9178** [comment]
This is due to you using gcov provided by XCode which is actually not gcov but llvm-cov with the gcov command as prefix. It does sadly not support the same arguments as real gcov and is therefore not supported. You can now use a suitable version of llvm-cov with upcoming 2.0.0 release
